# Generated by Django 3.1 on 2020-08-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='BodyShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Форма корпуса',
                'verbose_name_plural': 'Формы корпусов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Тип кабеля',
                'verbose_name_plural': 'Типы кабелей',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=40)),
                ('body_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('backlight', models.BooleanField(default=True)),
                ('tire_gilding', models.BooleanField(default=False)),
                ('usb_ports', models.BooleanField(default=True)),
                ('amount_of_rosette', models.IntegerField(default=9)),
                ('rosette_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('wire_length', models.IntegerField(blank=True)),
                ('body_shape', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='body_shapes', to='form.bodyshape')),
                ('rosette_manufacturer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='form.manufacturer')),
                ('wire_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wire_types', to='form.wiretype')),
            ],
            options={
                'verbose_name': 'Предзаполненная обратной связи',
                'verbose_name_plural': 'Предзаполненные обратной связи',
                'ordering': ('created',),
            },
        ),
    ]
