# Generated by Django 3.1 on 2020-08-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackform',
            options={'ordering': ('created',), 'verbose_name': 'Предзаполненная форма обратной связи', 'verbose_name_plural': 'Предзаполненные формы обратной связи'},
        ),
    ]
