# Generated by Django 3.1 on 2020-08-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_bodycolor_rosettecolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Цвет розеток',
                'verbose_name_plural': 'Цвета розеток',
            },
        ),
        migrations.DeleteModel(
            name='BodyColor',
        ),
        migrations.DeleteModel(
            name='RosetteColor',
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='amount_of_rosette',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='wire_length',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='form.Color'),
        ),
    ]
