# Generated by Django 3.1 on 2020-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20200828_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='body_colors',
            field=models.ManyToManyField(related_name='body_colors', to='form.Color'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='rosette_colors',
            field=models.ManyToManyField(related_name='rosette_colors', to='form.Color'),
        ),
    ]
