# Generated by Django 3.1 on 2020-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_remove_manufacturer_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Длинна кабеля',
                'verbose_name_plural': 'Длинна кабелей',
                'ordering': ('length',),
            },
        ),
    ]
