# Generated by Django 3.1 on 2020-08-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20200828_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wirelength',
            options={'ordering': ('length',), 'verbose_name': 'Длинна кабеля', 'verbose_name_plural': 'Длинна кабелей'},
        ),
        migrations.RemoveField(
            model_name='wirelength',
            name='name',
        ),
        migrations.AddField(
            model_name='wirelength',
            name='length',
            field=models.FloatField(default=1, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
