# Generated by Django 3.1 on 2020-09-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_auto_20200828_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='billingform',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='billingform',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='bodyshape',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Форма корпуса'),
        ),
        migrations.AlterField(
            model_name='color',
            name='alias',
            field=models.CharField(max_length=30, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Код цвета \n\nhttps://ru.wikipedia.org/wiki/%D0%A6%D0%B2%D0%B5%D1%82%D0%B0_HTML'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='amount_of_rosette',
            field=models.PositiveIntegerField(default=9, verbose_name='Количество розеток'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='body_color',
            field=models.CharField(default='#FFFFFF', max_length=10, verbose_name='Цвет корпуса'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='body_shape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='body_shapes', to='form.bodyshape', verbose_name='Форма корпуса'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='manufacturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='form.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='rosette_color',
            field=models.CharField(default='#FFFFFF', max_length=10, verbose_name='Цвет розеток'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='tire_gilding',
            field=models.BooleanField(default=False, verbose_name='Золочение шин'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='usb_ports',
            field=models.BooleanField(default=True, verbose_name='USB порты'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='wire_length',
            field=models.PositiveIntegerField(blank=True, verbose_name='Длинна кабеля'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='wire_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wire_types', to='form.wiretype', verbose_name='Тип кабеля'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='body_colors',
            field=models.ManyToManyField(related_name='body_colors', to='form.Color', verbose_name='Цвета корпуса'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='rosette_colors',
            field=models.ManyToManyField(related_name='rosette_colors', to='form.Color', verbose_name='Цвета розеток'),
        ),
        migrations.AlterField(
            model_name='wirelength',
            name='name',
            field=models.FloatField(max_length=100, verbose_name='Длинна кабеля'),
        ),
        migrations.AlterField(
            model_name='wiretype',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Тип кабеля'),
        ),
    ]
