# Generated by Django 3.1 on 2023-12-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_auto_20200904_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='backlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='body_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='form.color', verbose_name='Цвет корпуса'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='body_shape',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='body_shapes', to='form.bodyshape', verbose_name='Форма корпуса'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='form.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='rosette_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='form.color', verbose_name='Цвет розеток'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='usb_ports',
            field=models.BooleanField(default=False, verbose_name='USB порты'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='wire_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длинна кабеля'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='wire_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wire_types', to='form.wiretype', verbose_name='Тип кабеля'),
        ),
    ]
