# Generated by Django 3.1 on 2020-08-31 18:12

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to=news.models.upd_rand_name),
        ),
    ]
