# Generated by Django 3.1 on 2020-08-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
    ]
